### ISSUE TITLE
bug: prometheus label issues in 1.7.0

### ISSUE THREAD

**Issue by cdmbr** [RustedBones/akka-http-metrics#266]
Hi there

We were using path, status and method dimensions in our app

Something like:

```
 PrometheusSettings.default
   .withDurationConfig(Buckets(buckets: _*))
    .withDefineError(_.status.isFailure)
    .withIncludeMethodDimension(true)
    .withIncludePathDimension(true)
    .withIncludeStatusDimension(true)
    .withServerDimensions(
      Dimension("env", env),
      Dimension("stack", stack),
      Dimension("version", version)
    )
```

but it seems that the label values are been swapped e.g.

```
akka_http_responses_duration_seconds_bucket{env="prd",method="vacation",path="d6bfafe",stack="GET",status="/health/liveness",version="2xx",le="1.5",} 56.0
```

while in 1.6.0 it was working flawlessly
```
akka_http_responses_duration_seconds_bucket{env="prd",method="GET",path="/health/liveness",stack="vacation",status="2xx",version="d6bfafe",le="1.5",} 56.0
```

If I find some spare time, I will try to issue a PR to fix the issue :)

**Comment by cdmbr** [comment]
maybe related to https://github.com/RustedBones/akka-http-metrics/commit/f063d328e29987251337ef7e595f69883eff5b09

**Comment by RustedBones** [comment]
Dammit! I thought I fixed that before releasing 1.7.0. I must have overlooked something.

I'll not be able to work on that in the coming days, so feel free to open a PR!

Thanks a lot for the bug report @cdmbr

**Comment by RustedBones** [comment]
@cdmbr I released `1.7.1-SNAPSHOT`. Can you give it a try and if I get a :+1: , I'll release `1.7.1` ?

**Comment by cdmbr** [comment]
@RustedBones Thanks for fixing it 🥇  ... I'm not seeing the 1.7.1-SNAPSHOT in maven central yet 🤔  Have you published to a different repository ?

**Comment by RustedBones** [comment]
Yes, The artifact is published in the sonatype snapshot resolver. You must add
```sbt
resolvers += Resolver.sonatypeRepo("snapshots")
```

**Comment by cdmbr** [comment]
@RustedBones 

still getting some labels swapped 😢 :

```
akka_http_responses_size_bytes_bucket{env="local_env",method="local_stack",path="local_version",stack="GET",status="/metrics/prometheus",version="2xx",le="0.0",} 0.0
akka_http_responses_total{env="local_env",method="local_stack",path="local_version",stack="GET",status="/metrics/prometheus",version="2xx",} 2.0
```

config:

```
val prometheusSettings: PrometheusSettings = PrometheusSettings.default
    .withDurationConfig(Buckets(buckets: _*))
    .withDefineError(_.status.isFailure)
    .withIncludeMethodDimension(true)
    .withIncludePathDimension(true)
    .withIncludeStatusDimension(true)
    .withServerDimensions(
      Dimension("env", env),
      Dimension("stack", stack),
      Dimension("version", version)
    )
```

route:

```
  def routes: Route = pathLabeled("metrics" / "prometheus") {
    get { metrics(prometheusRegistry) }
  }
```

**Comment by RustedBones** [comment]
I'm not able to reproduce on the snapshot version.
Just making sure, did you reload the project after updating the version an re-running the tests ?

**Comment by cdmbr** [comment]
> I'm not able to reproduce on the snapshot version. Just making sure, did you reload the project after updating the version an re-running the tests ?

yes .... from 1.6.0 to 1.7.x Dimension is no longer a trait and the withServerDimensions receives an argument 😢 

but it seems that the release version is now working properly ... maybe I got a stale version of the snapshot 🤔 

anyway, thanks @RustedBones  !
